### PR TITLE
Added `Send Sms` and `Send Sms Unicode` code snippets

### PR DESCRIPTION
**Pull request by GregHolmes**
I've added these two code snippets so that I can work on getting this across to the NDP. If there are any issues please let me know.

### CODE REVIEW

**Comment by lornajane** [comment]
I screwed up something in testing and then realised the error handling on the send function isn't all that .... so, sorry, can we review and merge https://github.com/Vonage/vonage-go-sdk/pull/53 and then update this? There's a blog post in the wild as well.

**Comment by lornajane** [comment]
To make the snippets run locally I needed to add the dotenv library to turn the `.env` file into environment variables. Also Added a code update to take account of the library update linked above, so this PR is blocked until that merges.

**Comment by GregHolmes** [comment]
Hi @lornajane  I've updated `send-sms-unicode.go` to make use of the environment variables, and calling the Send() function now has the error response return parameter defined.

**Review by lornajane — APPROVED** [review]
Both working beautifully here. Nicely done!

**Pull request merged**
